import keyMirror from 'key-mirror';

export default keyMirror({
    GET_ADMIN_SUCCESS: null,
    GET_ADMIN_FAILURE: null,

    REGISTER_USER_SUCCESS:null,
    REGISTER_USER_FAILURE:null,
    
    REGISTER_ADMIN_SUCCESS:null,
    REGISTER_ADMIN_FAILURE:null,

    GET_ADMINMESSAGE_SUCCESS:null,
    GET_ADMINMESSAGE_FAILURE:null,
    
    UPDATE_ADMINMESSAGE_SUCCESS:null,
    UPDATE_ADMINMESSAGE_FAILURE:null,

    UPDATE_USERMESSAGE_SUCCESS:null,
    UPDATE_USERMESSAGE_FAILURE:null,

    GET_DISH_SUCCESS:null,
	GET_DISH_FAILURE:null,

	GET_ALLDISHES_SUCCESS:null,
	GET_ALLDISHES_FAILURE:null,

	ADD_DISH_SUCCESS:null,
	ADD_DISH_FAILURE:null,

	DELETE_DISH_SUCCESS:null,
	DELETE_DISH_FAILURE:null,

	UPDATE_DISH_SUCCESS:null,
	UPDATE_DISH_FAILURE:null,

	INSERT_DISH_SUCCESS:null,
	INSERT_DISH_FAILURE:null,

	GET_USERDISHES_SUCCESS:null,
	GET_USERDISHES_FAILURE:null,

	GET_ORDER_SUCCESS:null,
	GET_ORDER_FAILURE:null,

	UPDATE_ORDER_SUCCESS:null,
	UPDATE_ORDER_FAILURE:null,

	DELETE_ORDER_SUCCESS:null,
	DELETE_ORDER_FAILURE:null,
});